Updated create-release action
- The default input value no longer contains a 'v' because it was
misleading as the entered version shouldn't have the 'v'.
- The first action now validates the input to make sure the entered
version is in the expected format, and exits if it isn't.

diff --git a/.github/workflows/create-release.yml b/.github/workflows/create-release.yml
--- a/.github/workflows/create-release.yml
+++ b/.github/workflows/create-release.yml
@@ -6,7 +6,7 @@ on:
       new_version:
         description: 'Version for the new release'
         required: true
-        default: 'v5.x.x.x'
+        default: '5.x.x.x'
         type: string
 
 jobs:
@@ -14,6 +14,20 @@ jobs:
     name: Create release
     runs-on: ubuntu-latest
     steps:
+      - name: Validate entered version number
+        id: check-version
+        run: |
+          # Get entered version from inputs.
+          NEW_VERSION="${{ inputs.new_version }}"
+
+          # Validate the input.
+          if [[ ! "$NEW_VERSION" =~ ^([0-9]+)\.([0-9]+)\.([0-9]+)\.([0-9]+)$ ]]; then
+            echo "Error: NEW_VERSION '$NEW_VERSION' is not in valid format x.x.x.x"
+            exit 1
+          else
+            echo "Validation successful! Proceeding...
+          fi
+
       - name: Get auto-release app token
         uses: actions/create-github-app-token@v1
         id: get-app-token
@@ -33,13 +47,13 @@ jobs:
         run: |
           CSPROJ_PATH="./GeeksCoreLibrary/GeeksCoreLibrary.csproj"
 
-          # Extract current version
+          # Extract current version.
           CURRENT_VERSION=$(grep -oPm1 "(?<=<Version>)[^<]+" "$CSPROJ_PATH")
 
-          # Get latest version
+          # Get entered version from inputs.
           NEW_VERSION="${{ inputs.new_version }}"
 
-          # Update the .csproj file
+          # Update the .csproj file.
           sed -i "s|<Version>$CURRENT_VERSION</Version>|<Version>$NEW_VERSION</Version>|" "$CSPROJ_PATH"
           sed -i "s|<AssemblyVersion>$CURRENT_VERSION</AssemblyVersion>|<AssemblyVersion>$NEW_VERSION</AssemblyVersion>|" "$CSPROJ_PATH"
           sed -i "s|<FileVersion>$CURRENT_VERSION</FileVersion>|<FileVersion>$NEW_VERSION</FileVersion>|" "$CSPROJ_PATH"
